name: drlnd-p1
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - pip:
      - numpy==1.19.5
      - matplotlib==3.3.4
      - jupyter==1.0.0
      - torch==1.10.2
      - tensorflow==1.7.1
      - gym==0.9.6
      - unityagents==0.4.0
      - pyglet==1.5.11
      - box2d-py==2.3.5
      - protobuf==3.5.2
      - grpcio==1.11.0
      - docopt==0.6.2